#!/usr/bin/env python

import os
import sys
import types
import json
import getpass

try:
	import requests
	import argparse
except ImportError as error:
	print >>sys.stderr, "The modules argparse and requests are required. Please install them and try again."
	sys.exit(1)

webserver = os.environ.get('MCS_HOST')
username = os.environ.get('MCS_USERNAME')
password = os.environ.get('MCS_PASSWORD')
schema = os.environ.get('MCS_SCHEMA', 'https')
port = os.environ.get('MCS_PORT', 8443)

parser = argparse.ArgumentParser(
	description='Obtain the ansible inventory from a running MapR cluster.')
parser.add_argument('webserver', type=str,
	help='the hostname or IP of a node running mapr-webserver.')
parser.add_argument('--no-ssl', default=False, action='store_true',
	help='do not use SSL to connect.')
parser.add_argument('--port', default=8443, type=int,
	help='set the port number to connect to.')
parser.add_argument('--username', default='mapr', type=str,
	help='MCS username')
parser.add_argument('--password', default='mapr', type=str,
	help='MCS password')
parser.add_argument('--list', action='store_true')
parser.add_argument('--prompt', default=False, action='store_true',
	help='Prompt for MCS password. If this is set, passwords set via environment or command line are overridden.')

args = parser.parse_args()

if not (webserver or username or password):
	username = args.username
	password = args.password
	webserver = args.webserver

	if args.no_ssl:
		schema = "http"

if args.prompt:
	password = getpass.getpass("MCS Password for %s: " % username)
webserver_url = "%s://%s:%d/rest/node/list" % (schema, webserver, port)

params = { 'columns': 'hn,svc,csvc' }
try:
	r = requests.get(webserver_url, auth=(username,password), verify=False, params=params)
except requests.exceptions.ConnectionError as error:
	print >>sys.stderr, "Error connecting: %s" % error
	sys.exit(1)
	
try:
	r.raise_for_status()
except requests.exceptions.HTTPError as error:
	print >>sys.stderr, "Request was not successful: %s" % error
	sys.exit(1)

response = r.json()
data = response['data']

inventory = { }
for node in data:
	for service in node['configuredservice'].split(','):
		if service == 'hs2':
			service = 'hiveserver'
		inventory.setdefault(service, dict())
		inventory[service].setdefault('hosts', list())
		inventory[service].setdefault('vars', dict())
		inventory[service]['hosts'].append(node['ip'])	

print json.dumps(inventory)

